import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >

<nav className="bg-gray-900 text-white p-4">
  <div className="flex items-center justify-between">
   
    <div className="md:text-2xl font-extrabold text-transparent bg-clip-text bg-gradient-to-r from-purple-600 via-pink-500 to-red-500">
      Qaimudin
    </div>

    <div className="sm:flex space-x-6">
      <a href="/" className="text-[11px] md:text-[16px] hover:text-purple-400">Home</a>
      <a href="./Othergames" className="text-[11px] md:text-[16px] hover:text-purple-400">Other Games</a>
      <a href="./Contact" className="text-[11px] md:text-[16px] hover:text-purple-400">Contact</a>
    </div>
   </div>
</nav>

        {children}
      </body>
    </html>
  );
}
